config/routes.rb
Rails.application.routes.draw do
   root "departments#index"

   resources :departments do
    resources :items
   end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/department.rb
class Department < ApplicationRecord
  has_many :items
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :department
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/departments_controller.rb
class DepartmentsController < ApplicationController
   before_action :set_department, only: [:show, :edit, :update, :destroy]

  def index
    @departments = Department.all
  end

  def new
    @departments = Department.new
     render partial: "form"
  end

  def show
  end

    def create
      @department = Department.new(department_params)
    
      if @department.save
      redirect_to departments_path
      else
      render :new
      end
    end
    

    def edit
      render partial: "form"
    end

    def update 
      
      if @departments.update(department_params)
        redirect_to @departments
      else 
        render :edit
      end
    end

    def destroy
      @departments.destroy
      redirect_to departments_path
    end

    private
    def department_params
      params.require(:department).permit(:name)
    end

    def set_department
      @departments = Department.find(params[:id])
    end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_department
  before_action :set_item, only: [:show, :edit, :update, :destroy]

  def index
    @items = @department.items
  end

  def show
  end

  def new
    @item = @department.items.new
    render partial: "form"
  end

  def create
    @item = Department.items.new(topics_params)
  
    if @item.save
      redirect_to department_item_path(@department, @item)
    else
      render partial: "form"
    end
  end

  def edit
      render partial: "form"
  end

  def update

    if @items.update(items_params)
        redirect_to @items
    else
        render :edit
    end
  end

  def destroy
    @item.destroy
    redirect_to department_items_path(@department)

  end

  private
    
    def set_department
      @department = Department.find(params[:department_id])
    end

    def set_item
      @item = Item.find(params[:id])
    end

    def item_params
      params.require(:item).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/departments_helper.rb
module DepartmentsHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/departments/_form.html.erb
<h1><%= @departments.id ? 'Edit Department' : 'Create Department' %></h1>
<hr />
<%= form_for @departments do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name, required: true, autofocus: true %>
  <%= f.label :address %>
  <%= f.text_field :address, required: true, autofocus: true %>
  <%= f.label :phone %>
  <%= f.text_field :phone, required: true, autofocus: true %>

  <%= f.submit %>
<% end %>

app/views/departments/index.html.erb
<h1> Click a department to View Content</h1>
<%= link_to "Create a new department", new_department_path %>
<ul>
<% @departments.each do |department| %>
  <li><%= link_to department.name, department %></li>
  <% end %>
  </ul>

app/views/departments/new.html.erb
<h1>Departments</h1>
<%= form_for @departments do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :address %>
  <%= f.text_field :address %>

  <%= f.label :phone %>
  <%= f.text_field :phone %>

  <%= submit %>
  <% end %>

app/views/departments/show.html.erb
<h1><%= @departments.name %></h1>
<hr />
<p>"What would you like to do"</p>
  <%= link_to "view Items", department_items_path(@departments) %>
  <br />
  <%= link_to "Edit Department", edit_department_path(@departments) %>
  <br />
  <%= link_to "Delete Department", @department, method: :delete %>
  

app/views/items/_form.html.erb
<h1><%= @item.id ? 'Edit Item' : 'Create Item' %></h1>
<hr />
<%= form_for @item do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name, required: true, autofocus: true %>
  <%= f.submit %>
<% end %>

app/views/items/index.html.erb
<h1>Items#index</h1>
<p>Find me in app/views/items/index.html.erb</p>

app/views/items/new.html.erb
# <h1>Items#new</h1>
# <p>Find me in app/views/items/new.html.erb</p>

app/views/items/show.html.erb
<h1>Items#show</h1>
<p>Find me in app/views/items/show.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Store</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>